# Generated by Django 5.2 on 2025-10-16 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("book", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordsModel",
            fields=[
                (
                    "borrow_record_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("borrow_date", models.DateTimeField()),
                ("due_date", models.DateTimeField()),
                ("return_date", models.DateTimeField()),
                ("is_returned", models.BooleanField(default=False)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.bookmodel"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "record",
            },
        ),
        migrations.CreateModel(
            name="FineModel",
            fields=[
                (
                    "fine_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("paid", models.BooleanField(default=False)),
                ("issued_date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.FloatField()),
                (
                    "record_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records.recordsmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "fine",
            },
        ),
    ]
