# Generated by Django 5.2 on 2025-11-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recordsmodel",
            name="return_date",
            field=models.DateTimeField(blank=True),
        ),
    ]
