# Generated by Django 5.2 on 2025-10-16 16:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "category_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("description", models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "book_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                ("publisher", models.CharField(max_length=125)),
                ("summary", models.TextField(max_length=500)),
                ("cover_image", models.ImageField(upload_to="images/")),
                ("language", models.CharField(max_length=65)),
                ("total_copies", models.IntegerField()),
                ("published_year", models.DateTimeField()),
                (
                    "CategoryModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.categorymodel",
                    ),
                ),
            ],
        ),
    ]
