# Generated by Django 5.2 on 2025-11-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmodel",
            options={"verbose_name": "book"},
        ),
        migrations.AlterModelOptions(
            name="categorymodel",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="column",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="row",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name="bookmodel",
            name="section",
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="cover_image",
            field=models.ImageField(upload_to="media/images/"),
        ),
        migrations.AlterField(
            model_name="categorymodel",
            name="description",
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
