# Generated by Django 5.2 on 2025-11-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_alter_bookmodel_options_alter_categorymodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmodel",
            name="author",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="column",
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="row",
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="section",
            field=models.CharField(max_length=75),
        ),
    ]
