# Generated by Django 5.2 on 2025-11-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_bookmodel_author_alter_bookmodel_column_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmodel",
            old_name="CategoryModel",
            new_name="Category",
        ),
        migrations.AlterField(
            model_name="bookmodel",
            name="cover_image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
