# Generated by Django 5.2 on 2025-11-06 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_rename_categorymodel_bookmodel_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookmodel",
            old_name="Category",
            new_name="category",
        ),
    ]
