# Generated by Django 5.2 on 2025-11-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0005_rename_category_bookmodel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
