# Generated by Django 5.2 on 2025-11-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0006_alter_bookmodel_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.categorymodel",
            ),
        ),
    ]
